---
title: "Miniproject3"
author: "Dianne Caravela, Neyda Carrillo"
date: "4/16/2019"
output:   
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(macleish)
library(leaflet)
library(tidyverse)
library(sf)
library(rgdal)
```

```{r, warning=FALSE, message=FALSE}
macleish_trails <- macleish_layers %>%
  pluck("trails") %>%
  mutate(length = st_length(geometry))

macleish_elevation <- macleish_layers %>%
  pluck("contours_3m")

```

```{r, warning=FALSE, message=FALSE}
trail_elevations <- st_join(macleish_trails, macleish_elevation) %>%
  group_by(name) %>%
  mutate(min_elev = min(ELEV_FT), 
          max_elev = max(ELEV_FT), 
          change_elev = max_elev - min_elev,
          length_miles = length / 1609.344,
         difficulty_rating = sqrt(change_elev * 2 * length_miles)) %>%
  na.omit()
trail_elevations
```

```{r, message=FALSE}
rating <- colorNumeric(
  palette = "inferno",  
  domain = trail_elevations$difficulty_rating)

trail_map <- leaflet(data = trail_elevations) %>%
  addTiles() %>%
  addPolylines(color = ~rating(difficulty_rating)) %>%
  addLegend("topright", pal = rating, values = ~difficulty_rating, title = "Difficulty Rating", opacity = 1)
trail_map
```



